name: Relase

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/ci.yaml

  release:
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
      - uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Release to NPM
        run: pnpm publish --access public --no-git-checks

      - name: "Create Github Relase"
        uses: "softprops/action-gh-release@v3"
        with:
          generate_release_notes: true
