name: Relase

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/ci.yaml

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Release to NPM
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Create Github Relase"
        uses: "softprops/action-gh-release@v1"
        with:
          generate_release_notes: true
